# DATA
cyc_mode: discharge
data_path: data_spm_discharge
data_val_path: data_spm_discharge_val
enforce_licons: false
latent_dim: 128
n_param_pred: 6
n_points: 256
noise_factor: 1.0
scaler_path: data_spm_discharge/scaler_X.pkl
sim_config: spm_discharge.yaml
target_mode: phi

# ARCH
num_channels: 512 
num_convs: 2
num_fc_gamma_mu_hidden: 4
num_fc_gamma_mu_units: 2048
num_fc_hidden: 1
num_fc_units: 2048

# TRAIN
batch_size: 256
epochs: 1000
lr: 0.0001
models_dir: models

#SURROGATE
surrogate_model_recipe: training_recipes/recipe.yml


