# DATA
cyc_mode: discharge
data_path: ../1.gen_data/data_p2d_discharge
enforce_licons: false
latent_dim: 128
n_param_pred: 6
n_points: 256
noise_factor: 1.0
scaler_path: ../1.gen_data/data_p2d_discharge/scaler_X.pkl
sim_config: p2d_discharge_6par.yaml
target_mode: phi

# ARCH
num_channels: 512
num_convs: 2
num_fc_gamma_mu_hidden: 4
num_fc_gamma_mu_units: 2048
num_fc_hidden: 1
num_fc_units: 2048

# TRAIN
batch_size: 256
epochs: 20
lr: 0.0001
models_dir: models_p2d
# Path to a checkpoint to restart from (weights only); empty = train from scratch.
restart_from:

#SURROGATE
surrogate_model_recipe: ../2.surrogate/training_recipes/recipe_p2d.yml
